# Generated by Django 4.2.6 on 2023-11-04 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profiles_location_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='social_github',
            field=models.CharField(blank=True, max_length=222, null=True),
        ),
    ]
